title:            CWSI.PL
description:      Blog o e-commerce i automatyzacji z użyciem Python'a

# put your disqus here
disqus_shortname:
reading_time:     true # if true, shows the estimated reading time for a post
words_per_minute: 200
logo:             images/logo.png # logo visible in the topbar
excerpt_separator: <!-- more -->
# Your site's domain goes here (eg: //mmistakes.github.io, http://mademistakes.com, etc)
# When testing locally leave blank or use http://localhost:4000

url: https://chawel.github.io

# draw your top menu here
# each item must have a title and a url.
#   To list post categories. use type: 'categories'
#   To create sub categories. add a submenu item
# See the example
menu:
  - title: 'Start'
    url: '/'
  - title: 'Python'
    url: '#'
    submenu:
      - title: 'Skrypty'
        url: '/python/scripts'
      - title: 'Porady'
        url: '/python/tips'
      - title: 'Dla początkujących'
        url: '/python/tutorial'
  - title: 'E-commerce'
    url: '/ecommerce'
  - title: 'Tagi'
    url: '/tags'
  - title: 'Kategorie'
    url: '/categories'
    type: 'categories'
  - title: 'O mnie'
    url: '/about'

# Owner/author information
owner:
  name:           Paweł Chaniewski
  site:           http://cwsi.pl
  avatar:         images/avatar.jpg
  bio:            '"Im mniej nużącej pracy manualnej tym lepiej, zwłaszcza kiedy musimy sami prowadzić sklep internetowy". Autor bloga cwsi.pl o tematyce automatyzacji w dziedzinie e-commerce. Entuzjasta języków skryptowych (szczególnie Python).'
  email:          you@email.com
  # Twitter nick for use in Twitter cards and follow button.
  twitter: chawel # if no twitter in this config, the twitter follow button will be removed
  # GitHub nick for use in follow button in author block.
  github: chawel

# Twitter account associated with the site if different from owner/author twitter account.
# Used in Twitter cards.
twitter:

# Social networking links used in author block underneath posts. Update and remove as you like.
social:
  - title: "github"
    url: "https://github.com/chawel"
  # - title: "linkedin"
  #   url: "https://br.linkedin.com/in/aronbordin"
  - title: "youtube"
    url: "https://www.youtube.com/channel/UC1ahnO3PNRSEe77_Ogvm5Yg"

# Background image to be tiled on all pages
background:

# Analytics and webmaster tools stuff goes here
google_analytics:
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
date_format: '%-d %B %Y'
lang:        pl
timezone:    Europe/Warsaw
locale:      pl_PL
future:      true
highlighter: rouge
markdown:    kramdown
sass:
  sass_dir: _sass
  style: compressed

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title/

# Amount of post to show on home page
paginate: 5

# if true, shows the floatting share buttons
float_share: false

# Octopress
# Default extensions
post_ext: md
page_ext: md
# Found in _templates/
post_layout: post
page_layout: page
# Format titles with titlecase?
titlecase: true

include: [".htaccess"]
exclude: ["demo/*", "lib", "config.rb", "Capfile", "config", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]
plugins: [jekyll-paginate]
# theme: neo-hpstr-jekyll-theme
